# -*- coding: utf-8 -*-
"""BaccoEmulator_Nonlinear_Total_Spectrum.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYN3wedBtApg98qr7Mh3K99PjNyBmUpR

- # Installation
"""

pip install -q baccoemu

"""- # Import Libraries and Load Emulator"""

import warnings
import numpy as np
import matplotlib.pyplot as plt
import baccoemu
warnings.filterwarnings('ignore')

# Load the matter power spectrum emulator
emulator = baccoemu.Matter_powerspectrum(verbose=False)

"""- # Define Wavemodes Vector and Cosmological Parameters"""

# Define wavemodes vector using the maximum k from nonlinear emulator
k = np.logspace(-2, np.log10(emulator.emulator['nonlinear']['k'].max()), num=100)

# Define cosmological parameters
params = {
    'omega_cold'    :  0.315,
    'sigma8_cold'   :  0.83,  # if A_s is not specified
    'omega_baryon'  :  0.05,
    'ns'            :  0.96,
    'hubble'        :  0.67,
    'neutrino_mass' :  0.0,
    'w0'            : -1.0,
    'wa'            :  0.0,
    'expfactor'     :  1
}

"""- # Evaluate Power Spectra and Nonlinear Boost"""

# Evaluate nonlinear boost (Q factor) for total matter only
k, Q_total = emulator.get_nonlinear_boost(k=k, cold=False, **params)

# Evaluate nonlinear power spectrum for total matter only
k, pk_nl_total = emulator.get_nonlinear_pk(k=k, cold=False, **params)

"""- # Plot Results"""

# Plot the results
fig, ax = plt.subplots(1, 2, figsize=(10, 5))

# Plot nonlinear boost for total matter
ax[0].loglog(k, Q_total, label='Total matter boost')
ax[0].set_xlabel("k [h/Mpc]")
ax[0].set_ylabel("Q")
ax[0].set_title("Nonlinear Boost")
ax[0].legend()

# Plot nonlinear power spectrum only
ax[1].loglog(k, pk_nl_total, label="Nonlinear Power Spectrum (total)")
ax[1].set_xlabel("k [h/Mpc]")
ax[1].set_ylabel("P(k)")
ax[1].set_title("Nonlinear Power Spectrum")
ax[1].legend()

plt.tight_layout()
plt.show()