ls ../../../


cd ~                    # Go to home
ls -l                   # See all files/folders
cd Documents            # (If you have a folder called Documents)
ls -l                   # View files in that folder
