# -*- coding: utf-8 -*-
"""cosmo_mcmc_test_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAtwOWUF4h2VVyavBOAbMQe0WScHFT5I

# Galaxy–CMB Lensing Cross-Correlation Pipeline for Cosmological Parameter Inference


## **Fundamental Cosmological Functions**

### **Hubble Function**
**Equation (68):**
```
H(z) = H₀ √[Ωₘ(1+z)³ + Ωₗ]
```
- **Physical meaning**: Expansion rate of the universe at redshift z
- **Components**: Matter density Ωₘ dominates at high z, dark energy Ωₗ at low z

### **Comoving Distance**
```
χ(z) = ∫₀ᶻ c/H(z') dz'
```
- **Physical meaning**: Distance to object at redshift z in comoving coordinates
- **Integration**: Numerical integration over cosmic time

### **Growth Factor**
**Equation (66):**
```
D(z) = g(z)/(1+z)
```

**Growth Function (Equation 67):**
```
g(z) = (5Ω(z)/2) × 1/[Ω(z)^(4/7) - λ(z) + (1 + Ω(z)/2)(1 + λ(z)/70)]
```

**Where:**
```
Ω(z) = Ωₘ(1+z)³ / [Ωₘ(1+z)³ + (1-Ωₘ-Ωₗ)(1+z)² + Ωₗ]    (Eq. 68)

λ(z) = Ωₗ / [Ωₘ(1+z)³ + (1-Ωₘ-Ωₗ)(1+z)² + Ωₗ]              (Eq. 69)
```

- **Physical meaning**: How density perturbations grow with cosmic time

## **Lensing Kernel Functions**

### **CMB Lensing Kernel**
**Equation (4.2):**
```
W_κ(z) = (3ΩₘH₀²)/(2c) × (1+z) × χ(z) × [χ* - χ(z)]/χ*
```
- **χ***: Comoving distance to CMB surface (z* ≈ 1100)
- **Physical meaning**: Lensing efficiency of matter at redshift z on CMB photons

### **Galaxy Lensing Kernel**
**Equations (4.3) and (4.4):**
```
W_g(z) = b(z) × dN/dz + μ(z)
```

**Magnification term (4.4):**
```
μ(z) = (3ΩₘH₀²)/(2c) × (1+z) × χ(z) × ∫_z^∞ [1 - χ(z)/χ(z')] × (α-1) × dN/dz'(z') dz'
```

**Galaxy bias (4.7):**
```
b(z) = b₀/D*(z)
```
- **α = 2.225**: Magnification bias parameter
- **Physical meaning**: How galaxy observations are affected by lensing magnification

## **Power Spectrum Calculations**

### **CosmoPower Neural Network**
**Input parameters:**
```
θ = {Ωᵦh², Ωᶜh², h, nₛ, ln(10¹⁰Aₛ), z}
```
**Output:**
```
P(k,z) = NN_CosmoPower(θ)
```
- **Physical meaning**: Matter power spectrum at wavenumber k and redshift z

### **Limber Approximation**
**3D → 2D projection:**
```
C_ℓ = ∫₀^∞ dz × H(z)/χ²(z) × W_X(z) × W_Y(z) × P(k = ℓ/χ(z), z)
```
- **Simplified form:**
```
C_ℓ ≈ P(k = ℓ/χ, z)/χ²
```
- **Physical meaning**: Projects 3D matter correlations to 2D angular correlations

## **Cross-Correlation Analysis**

### **Galaxy-CMB Cross-Correlation**
**Full Limber integral:**
```
C_ℓ^(gκ) = (1/c) ∫₀^∞ dz × H(z)/χ²(z) × W_g(z) × W_κ(z) × P_mm(ℓ/χ(z), z)
```

**Practical approximation:**
```
C_ℓ^(gκ) = b_g × η_lens × √[P_g(ℓ/χ_eff, z_g) × P_κ(ℓ/χ_eff, z_κ)] / χ_eff²
```

**Where:**
- **χ_eff = √(χ_g × χ_κ)**: Effective distance
- **η_lens**: Lensing efficiency factor
- **b_g**: Galaxy bias

### **Lensing Efficiency**
```
η_lens = W_κ(z_g, z*) / W_κ(z_κ, z*)
```

**CMB Lensing Weight:**
```
W_κ(z, z*) = (3ΩₘH₀²)/(2c) × (1+z) × χ(z) × [χ* - χ(z)]/χ*
```

## **Statistical Framework**

### **Covariance Matrix**
**Cosmic variance formula:**
```
Cov(C_ℓ^XY) = δ_ℓℓ' × 1/((2ℓ+1)f_sky) × [C_ℓ^XX × C_ℓ^YY + (C_ℓ^XY)²]
```

**For galaxy-CMB cross-correlation:**
```
Cov(C_ℓ^gκ) = 2 × C_ℓ^gg × C_ℓ^gκ / [(2ℓ+1) × f_sky]
```
- **f_sky**: Fraction of sky observed
- **Physical meaning**: Statistical uncertainty from finite survey volume

### **Log-Likelihood Function**
**Chi-squared statistic:**
```
χ² = (C_ℓ^model - C_ℓ^data)ᵀ × Cov⁻¹ × (C_ℓ^model - C_ℓ^data)
```

**Log-likelihood:**
```
ln ℒ = -½χ²
```

**Posterior probability (Bayes' theorem):**
```
P(θ|D) ∝ ℒ(D|θ) × π(θ)
```
- **θ**: Cosmological parameters {H₀, Ωᵦh², Ωᶜh², nₛ, Aₛ}
- **π(θ)**: Prior probability distributions

## **Parameter Conversions**

### **Standard Cosmological Parameters**
```
h = H₀/100                    [dimensionless Hubble parameter]
Ωᵦ = Ωᵦh²/h²                 [baryon density parameter]  
Ωᶜ = Ωᶜh²/h²                 [cold dark matter density]
Ωₘ = Ωᵦ + Ωᶜ                 [total matter density]
Ωₗ = 1 - Ωₘ                  [dark energy density, flat universe]
Aₛ = exp(ln(10¹⁰Aₛ))/10¹⁰   [primordial scalar amplitude]
```

### **Physical Constants**
```
c = 299,792.458 km/s         [speed of light]
α = 2.225                    [magnification bias parameter]
z* ≈ 1100                    [CMB surface redshift]
```

## **Observational Setup**

### **Survey Parameters**
```
z_g = 0.5                    [galaxy survey redshift]
z_κ = 1.0                    [effective lensing redshift]  
f_sky = 0.1                  [sky fraction = 10%]
ℓ_max = 200                  [maximum angular scale]
ℓ_min = 2                    [minimum angular scale]
```

### **Prior Distributions**
```
H₀ ~ Uniform(H₀_fid - 10, H₀_fid + 10)     [km/s/Mpc]
Ωᵦh² ~ Normal(0.0225, 0.003²)              [baryon density]
Ωᶜh² ~ Normal(0.113, 0.015²)               [DM density]  
nₛ ~ Normal(0.96, 0.015²)                  [spectral index]
Aₛ ~ Normal(A_fid, (3×10⁻¹⁰)²)            [primordial amplitude]
```

## **Key Physical Scales**

### **Angular Scales**
```
θ ≈ 1/ℓ                     [angular scale in radians]
θ_deg ≈ 180°/(π×ℓ)          [angular scale in degrees]
```

### **Physical Scales**
```
k = ℓ/χ(z)                  [comoving wavenumber]
λ = 2π/k                    [comoving wavelength]  
λ_phys = λ/(1+z)            [physical wavelength]
```

---

**Mathematical Framework**: This analysis implements the full theoretical framework for multi-probe cosmology, combining galaxy clustering, weak lensing, and CMB observations to constrain fundamental cosmological parameters through Bayesian inference.
"""

pip install -q pocomc cosmopower astropy getdist corner gdown  # Install all required packages

#pip show pocomc cosmopower astropy getdist corner gdown

import pkg_resources

packages = ['pocomc', 'cosmopower', 'astropy', 'getdist', 'gdown', 'corner']

for package in packages:
    try:
        version = pkg_resources.get_distribution(package).version
        print(f"{package} version: {version}")
    except pkg_resources.DistributionNotFound:
        print(f"{package} is not installed.")

"""## Fiducial Cosmological Parameters

The fiducial parameter values used for generating synthetic spectra:

| Parameter     | Symbol         | Value         |
|---------------|----------------|---------------|
| Hubble const. | H₀             | 70.0 km/s/Mpc |
| Baryon dens.  | Ω<sub>b</sub>h² | ~0.011        |
| CDM dens.     | Ω<sub>c</sub>h² | ~0.035        |
| Spectral index| n<sub>s</sub>   | 0.96          |
| Scalar amp.   | A<sub>s</sub>   | 2.14 × 10⁻⁹   |

"""

# Library Imports and Setup
# (Import essential libraries for cosmological modeling, statistical sampling,
# power spectrum emulation, numerical integration, and data visualization)

import os                     # For operating system interactions
import gdown                  # To download files from Google Drive
import numpy as np            # For numerical operations
import matplotlib.pyplot as plt  # For plotting graphs
from scipy.stats import uniform, norm  # For statistical distributions
import pocomc as pc           # For Population Monte Carlo (PoCoMC) sampling
import cosmopower as cp       # For fast cosmological power spectrum emulation
from astropy.cosmology import FlatLambdaCDM  # Define flat Lambda-CDM cosmology
from astropy.cosmology import Planck18        # Predefined Planck 2018 cosmological model
from scipy.integrate import quad  # For numerical integration
import getdist                # For analyzing and plotting MCMC chains
from getdist import MCSamples, plots  # Tools for MCMC output visualization
import corner                 # For corner plots of posterior distributions

# Parameter Dictionary Setup (Create a Dictionary of Fiducial (reference) Cosmological Parameters)

params = {'omega_b': [0.0225],         # Baryon density parameter
          'omega_cdm': [0.113],        # Cold dark matter density parameter
          'h': [0.7],                  # Dimensionless Hubble parameter (H₀ / 100)
          'tau_reio': [0.055],         # Reionization optical depth
          'n_s': [0.96],               # Scalar spectral index
          'ln10^{10}A_s': [3.07],      # Log amplitude of primordial scalar perturbations
          }

# Define constants (Physical Constants)
c = 299792.458  # km/s (speed of light)
alpha = 2.225  # Magnification bias parameter (Affects lensing observables. Controls how galaxy magnification affects observed number counts)

# CosmoPower Model Setup
# --- Step 1: Set Up CosmoPower Emulator ---
# Download the pre-trained CosmoPower model

os.makedirs("home", exist_ok=True) #Creates necessary directories
os.makedirs("plots", exist_ok=True)

# Download the model (a pre-trained neural network model for linear matter power spectra)
gdown.download('https://drive.google.com/uc?id=1h-IxTLoyTE6L3_uE9omjDNC-8X_uVAie', 'home/PKLIN_NN.pkl', quiet=False)

# Load pre-trained CosmoPower model for linear P(k)
cp_nn = cp.cosmopower_NN(restore=True, restore_filename='home/PKLIN_NN')

"""
# Computes the Hubble parameter H(z) at a given redshift z using the Friedmann equation.

Overview:
---------
The Hubble parameter H(z) describes the expansion rate of the universe at redshift z.
This implementation assumes a flat ΛCDM cosmological model (Ω_k = 0) and neglects radiation.
Constant Dark Energy (w = -1)

Final Form:
-----------
    H(z) = H₀ × sqrt[Ωₘ (1 + z)³ + Ω_Λ]

Where:
-------
- H(z)      : Hubble parameter at redshift z
- H₀        : Present-day Hubble constant
- Ωₘ        : Present-day matter density parameter
- Ω_Λ       : Present-day dark energy density parameter (cosmological constant)
- z         : Redshift

Derivation from Lahav et al. (2004), Eq. (68) and (69):
-------------------------------------------------------
Equation (68) defines:
    Ω(z) = Ωₘ (1 + z)³ × [H₀ / H(z)]²

Rearranging to isolate H(z):
    [H(z)/H₀]² = Ωₘ (1 + z)³ / Ω(z)

From the definition of Ω(z) that includes both matter and dark energy components:
    Ω(z) = Ωₘ (1 + z)³ / [Ωₘ (1 + z)³ + Ω_Λ]

Substituting into the previous expression yields:
    H²(z) = H₀² [Ωₘ (1 + z)³ + Ω_Λ]

Thus:
    H(z) = H₀ × sqrt[Ωₘ (1 + z)³ + Ω_Λ]

Extended Context:
-----------------
Full Friedmann equation (not used here but shown for completeness):
    H²(z) = H₀² [Ω_r (1 + z)⁴           # Radiation
                 + Ωₘ (1 + z)³          # Matter
                 + Ω_k (1 + z)²         # Curvature
                 + Ω_Λ]                # Dark Energy"""

# Core Cosmological Functions
# --- Step 2: Helper Functions Based on Standard Cosmological Equations ---


# Friedmann Equation (for flat universe)

def hubble_function(z, H0, Om_m, Om_lambda): # Hubble Function (Computes the Hubble parameter H(z) at redshift z using the Friedmann equation)
                                             # Computes H(z) - how fast the universe expands at redshift z
                                             # From Friedmann equation: H²(z) = H₀²[Ωₘ(1+z)³ + Ωₗ]

    """
    Hubble function H(z) (Eq. 68, Lahav et al., 2004)
    """
    return H0 * np.sqrt(Om_m * (1 + z)**3 + Om_lambda)


# Line-of-Sight Comoving Distance/Proper Comoving Distance/Comoving Radial Distance

def comoving_distance_proper(z, H0, Om_m, Om_lambda): # Comoving Distance (Calculates comoving distance by integrating c/H(z) from redshift 0 to z)
                                                      # Calculates comoving distance χ(z) - the distance to an object at redshift z
                                                      # Physics: χ(z) = ∫₀ᶻ c/H(z') dz'
    """
    Proper comoving distance calculation using chi(z) = integral of c/H(z) dz
    """
    def integrand(z_prime):
        return c / hubble_function(z_prime, H0, Om_m, Om_lambda)

    chi, _ = quad(integrand, 0, z)
    return chi

#  Linear Growth Factor D(z) in ΛCDM Cosmology

def growth_factor_D(z, H0, Om_m, Om_lambda): # Growth Factor Functions (Computes the linear growth factor D(z))
                                                                    # growth function g(z) that describe how density perturbations grow over cosmic time)
                                                                    # Computes D(z) - how much density perturbations have grown since redshift z
                                                                    # Physics: D(z) = g(z)/(1+z), where g(z) is the growth function
                                                                    # (Analytical approximation for structure growth in ΛCDM cosmology)

    """
    Growth factor D(z) : D(z) = g(z)/(1+z) (Eq. 66, Lahav et al., 2004)
    """
    g_z = growth_function_g(z, H0, Om_m, Om_lambda) #
    return g_z / (1 + z)

# Growth Function g(z) in ΛCDM Cosmology

def growth_function_g(z, H0, Om_m, Om_lambda):
    """
    Growth function g(z) (Eq. 67, Lahav et al., 2004)
    """
    # Compute Omega(z) and lambda(z) from equations (68) and (69)
    Omega_z = compute_Omega_z(z, H0, Om_m, Om_lambda)
    lambda_z = compute_lambda_z(z, H0, Om_m, Om_lambda)

    # Equation (67): g(z) = (5*Omega(z)/2) * 1/(Omega(z)^(4/7) - lambda(z) + [1+Omega(z)/2][1+lambda(z)/70])
    denominator = Omega_z**(4/7) - lambda_z + (1 + Omega_z/2) * (1 + lambda_z/70)
    g_z = (5 * Omega_z / 2) * (1 / denominator)

    return g_z

# Matter Density Parameter Ω(z) in ΛCDM Cosmology

def compute_Omega_z(z, H0, Om_m, Om_lambda):
    """
    Compute Omega(z) (Eq. 68, Lahav et al., 2004)
    """
    H_z = hubble_function(z, H0, Om_m, Om_lambda)
    numerator = Om_m * (1 + z)**3
    denominator = Om_m * (1 + z)**3 + (1 - Om_m - Om_lambda) * (1 + z)**2 + Om_lambda
    return numerator / denominator

# Cosmological Constant Density Parameter λ(z) in ΛCDM Cosmology

def compute_lambda_z(z, H0, Om_m, Om_lambda):
    """
    Compute lambda(z) (Eq. 69, Lahav et al., 2004)
    """
    H_z = hubble_function(z, H0, Om_m, Om_lambda)
    numerator = Om_lambda
    denominator = Om_m * (1 + z)**3 + (1 - Om_m - Om_lambda) * (1 + z)**2 + Om_lambda
    return numerator / denominator

# Lensing Kernel Functions

# CMB Lensing Kernel W_κ(z)

def cmb_lensing_kernel(z, z_star, H0, Om_m, Om_lambda):  # CMB Lensing Kernel (Computes the lensing kernel W_κ(z)
                                                        # that describes how matter at different redshifts contributes to CMB lensing)
    """
    CMB lensing kernel W_k(z) (Eq. 4.2, Karim et al., 2025)
    W_k(z) = (3*Omega_M * H0^2)/(2*c) * (1+z) * chi(z) * (chi_star - chi(z))/chi_star
    """
    chi_z = comoving_distance_proper(z, H0, Om_m, Om_lambda)
    chi_star = comoving_distance_proper(z_star, H0, Om_m, Om_lambda)

    # Equation (4.2)
    prefactor = (3 * Om_m * H0**2) / (2 * c)
    kernel = prefactor * (1 + z) * chi_z * (chi_star - chi_z) / chi_star

    return kernel


# Galaxy Lensing Kernel W_g(z)
# Computes the total galaxy lensing kernel, which includes contributions from:
# 1. Galaxy bias (b(z)·dN/dz) – representing the clustering of galaxies as tracers of the matter field
# 2. Magnification bias μ(z) – due to gravitational lensing affecting the observed galaxy number density
#
# Formula: W_g(z) = b(z)·dN/dz + μ(z)
# - μ(z) is calculated using:
#   μ(z) = [(3 * Ωₘ * H₀²) / (2c)] × (1 + z) × χ(z) × ∫ₓ^z* [1 - χ(z)/χ(z')]·(α - 1)·dN/dz' dz'
# Assumes a high redshift cutoff z* ≈ 10 for the upper limit of the magnification integral
# Reference: Eq. 4.3 and 4.4, Karim et al., 2025


def galaxy_lensing_kernel(z, z_array, dN_dz_func, bias_func, H0, Om_m, Om_lambda): # Galaxy Lensing Kernel (Computes the galaxy lensing kernel W_g(z) including both
                                                                                   # galaxy bias and magnification effects)
    """
    Galaxy lensing kernel W_g(z) (Eq. 4.3 and 4.4, Karim et al., 2025)
    W_g(z) = b(z) * dN/dz + mu(z)
    """
    # Bias term
    bias_term = bias_func(z) * dN_dz_func(z)

    # Magnification term mu(z) (Eq. 4.4, Karim et al., 2025)
    chi_z = comoving_distance_proper(z, H0, Om_m, Om_lambda)

    # Compute the integral term in mu(z)
    def integrand(z_prime):
        chi_z_prime = comoving_distance_proper(z_prime, H0, Om_m, Om_lambda)
        return (1 - chi_z / chi_z_prime) * (alpha - 1) * dN_dz_func(z_prime)

    # Integrate from z to z_star (assuming z_star is large)
    z_star = 10.0  # Approximate value
    integral_term, _ = quad(integrand, z, z_star)

    # (Eq. 4.4, Karim et al., 2025)
    mu_prefactor = (3 * Om_m * H0**2) / (2 * c) * (1 + z) * chi_z
    mu_z = mu_prefactor * integral_term

    return bias_term + mu_z

# Galaxy Bias Function b(z)

def bias_function(z):
    """
    Simple bias function b(z) = b0/D*(z) (Eq. 4.7, Karim et al., 2025)
    """
    b0 = 1.0  # Fiducial bias at z=0
    # D*(z) is the growth factor normalized to today
    D_star_z = growth_factor_D(z, 70.0, 0.3, 0.7) / growth_factor_D(0, 70.0, 0.3, 0.7)
    return b0 / D_star_z

# Galaxy Redshift Distribution dN/dz

def galaxy_number_density(z):
    """
    Simple galaxy number density model dN/dz
    """
    z0 = 0.3
    return np.exp(-z/z0)


# Cross-Correlation Angular Power Spectrum C_XY(ℓ) using the Limber Approximation
# Computes the cross-spectrum between two tracers (e.g., galaxies and CMB lensing)
# Formula:
#   C_XY(ℓ) = (1/c) ∫ₓ₁ᶻ₂ [H(z) / χ²(z)] · W_X(z) · W_Y(z) · P_mm(k=ℓ/χ(z), z) dz
# where:
# - H(z) is the Hubble parameter
# - χ(z) is the comoving distance
# - W_X(z), W_Y(z) are lensing kernels (CMB or galaxy)
# - P_mm(k, z) is the matter power spectrum evaluated at k = ℓ/χ(z)
#
# This implementation assumes:
# - Limber approximation (valid for ℓ ≳ 10)
# - A simple power-law form for P_mm(k, z)
# - CMB lensing if z > 5, galaxy lensing otherwise

def cross_correlation_spectrum_proper(z1, z2, H0, Om_m, Om_lambda, lmax=1000):
    """
    Proper cross-correlation spectrum using the Limber approximation
    C_XY(l) = (1/c) * integral[z1 to z2] H(z)/chi^2(z) * W_X * W_Y * P_mm(k=l/chi(z), z) dz
    """
    ell = np.arange(2, lmax + 1)

    # Define redshift range for integration
    z_min = min(z1, z2)
    z_max = max(z1, z2)
    z_array = np.linspace(z_min, z_max, 50)

    C_ell = np.zeros_like(ell, dtype=float)

    for i, l in enumerate(ell):
        def integrand(z):
            chi_z = comoving_distance_proper(z, H0, Om_m, Om_lambda)
            H_z = hubble_function(z, H0, Om_m, Om_lambda)

            # Compute kernels
            if z1 > 5:  # CMB lensing
                W_X = cmb_lensing_kernel(z, z1, H0, Om_m, Om_lambda)
            else:  # Galaxy lensing
                W_X = galaxy_lensing_kernel(z, z_array, galaxy_number_density, bias_function, H0, Om_m, Om_lambda)

            if z2 > 5:  # CMB lensing
                W_Y = cmb_lensing_kernel(z, z2, H0, Om_m, Om_lambda)
            else:  # Galaxy lensing
                W_Y = galaxy_lensing_kernel(z, z_array, galaxy_number_density, bias_function, H0, Om_m, Om_lambda)

            # Get matter power spectrum at k = l/chi(z)
            k = l / chi_z
            # Here we would need P_mm(k, z) - using simplified approximation
            P_mm = 1e-3 * (k/0.1)**(-1.5)  # Simplified power spectrum

            return (H_z / chi_z**2) * W_X * W_Y * P_mm

        integral_result, _ = quad(integrand, z_min, z_max)
        C_ell[i] = (1/c) * integral_result

    return ell, C_ell




# Matter Power Spectrum P(k, z) using CosmoPower Emulator
# Generates the nonlinear matter power spectrum P(k) at a given redshift z
# Uses pre-trained neural network emulator from CosmoPower
# Input parameters (H₀, Ω_b h², Ω_c h², n_s, A_s) are converted to the format required by the emulator:
#   - omega_b = Ω_b = Ω_b h² / h²
#   - omega_cdm = Ω_cdm = Ω_c h² / h²
#   - h = H₀ / 100
#   - ln(10¹⁰ A_s) is passed directly
# Returns the predicted P(k) array at the specified redshift

# Power Spectrum Calculations (CosmoPower Interface)
# Interfaces with CosmoPower to quickly compute the matter power spectrum P(k,z) for given cosmological parameters

def run_cosmopower(H0, ombh2, omch2, ns, As, z):
    """
    Run CosmoPower to get P(k) at given redshift z.
    Fixed: Proper parameter conversion and handling.
    """
    h = H0 / 100.0

    # Prepare the cosmological parameters
    cosmology_params = {
        'omega_b': [ombh2 / h**2],
        'omega_cdm': [omch2 / h**2],
        'h': [h],
        'n_s': [ns],
        'ln10^{10}A_s': [np.log(As * 1e10)],
        'z': [z]
    }

    # CosmoPower prediction of P(k)
    result = cp_nn.ten_to_predictions_np(cosmology_params)
    spectrum_cp = result[0]  # The actual matter power spectrum P(k)

    return spectrum_cp


# Retrieve k-Modes Used by CosmoPower Emulator
# Returns the array of wavenumbers k [in h/Mpc] used for evaluating P(k)
# Typically, CosmoPower models are trained on a log-spaced grid: k ∈ [10⁻⁴, 10¹] h/Mpc
# This function ensures compatibility with CosmoPower’s expected input/output structure
# Default length set to 100 for manageable resolution; adjust as needed for full fidelity

def get_k_modes():
    """
    Get the k-modes that CosmoPower uses.
    This should match the training grid of CosmoPower.
    """
    # First try to get the actual k-modes from CosmoPower
    # If not available, use the standard range
    try:
        # CosmoPower typically uses this k range - but let's be more conservative
        # about the length to match what CosmoPower actually returns
        return np.logspace(-4, 1, 100)  # Reduced from 256 to 100
    except:
        # Fallback
        return np.logspace(-4, 1, 100)



# Comoving Distance χ(z) using astropy.cosmology
# Computes the comoving line-of-sight distance to redshift z in a flat ΛCDM universe
# Uses astropy's FlatLambdaCDM with specified H₀ and Ωₘ
# Returns the comoving distance in megaparsecs (Mpc)
# Equivalent to: χ(z) = ∫₀ᶻ c / H(z') dz'


def comoving_distance(z, H0, Om0):
    """
    Compute comoving distance using integration.
    Fixed: Use proper cosmological parameters.
    """
    cosmo = FlatLambdaCDM(H0=H0, Om0=Om0)
    return cosmo.comoving_distance(z).value  # Mpc


# Limber Projection
# Projects 3D matter power spectrum to 2D angular power spectrum using the Limber approximation

def limber_projection(P_k_z, z_proj, H0, Om0, lmax=1000):
    """
    Project 3D P(k,z) to 2D C_l using Limber approximation.
    Fixed: Proper implementation of Limber projection.
    """
    ell = np.arange(2, lmax + 1)
    chi = comoving_distance(z_proj, H0, Om0)

    # Get k-modes from CosmoPower
    k_modes = get_k_modes()

    # Ensure P_k_z has the same length as k_modes
    if len(P_k_z) != len(k_modes):
        # If lengths don't match, take the minimum and truncate both
        min_len = min(len(P_k_z), len(k_modes))
        P_k_z = P_k_z[:min_len]
        k_modes = k_modes[:min_len]

    # For each ell, compute k = ell/chi
    k_vals = (ell + 0.5) / chi

    # Interpolate P(k, z) at these k values
    P_k_interp = np.interp(k_vals, k_modes, P_k_z)

    # Limber approximation: C_l = P(k=l/chi, z) / chi^2
    # Include proper normalization
    C_ell = P_k_interp / chi**2

    return ell, C_ell

# Cross-Correlation Analysis
# Computes the cross-correlation between galaxy positions and CMB lensing, accounting for galaxy bias and lensing efficiency

def galaxy_cmb_cross_spectrum(P_k_z_g, P_k_z_k, z_g, z_k, H0, Om0, b_g=1.0, lmax=1000):
    """
    Compute galaxy-CMB lensing cross-correlation using proper formalism.
    Enhanced with proper lensing kernels.
    """
    ell = np.arange(2, lmax + 1)

    # Comoving distances
    chi_g = comoving_distance(z_g, H0, Om0)
    chi_k = comoving_distance(z_k, H0, Om0)

    # Use geometric mean for effective distance
    chi_eff = np.sqrt(chi_g * chi_k)

    # k-modes
    k_modes = get_k_modes()

    # Ensure both P_k arrays have the same length as k_modes
    min_len = min(len(P_k_z_g), len(P_k_z_k), len(k_modes))
    P_k_z_g = P_k_z_g[:min_len]
    P_k_z_k = P_k_z_k[:min_len]
    k_modes = k_modes[:min_len]

    k_vals = (ell + 0.5) / chi_eff

    # Interpolate both power spectra
    P_k_g_interp = np.interp(k_vals, k_modes, P_k_z_g)
    P_k_k_interp = np.interp(k_vals, k_modes, P_k_z_k)

    # Cross-correlation (geometric mean approximation)
    P_k_cross = np.sqrt(P_k_g_interp * P_k_k_interp)

    # Include bias for galaxies and proper lensing efficiency
    Om_lambda = 1 - Om0  # Assuming flat universe
    lensing_efficiency = compute_lensing_efficiency_proper(z_g, z_k, H0, Om0, Om_lambda)

    # Enhanced cross-correlation C_l with proper kernels
    C_ell = b_g * lensing_efficiency * P_k_cross / chi_eff**2

    return ell, C_ell

def compute_lensing_efficiency_proper(z_g, z_k, H0, Om0, Om_lambda):
    """
    Compute proper lensing efficiency factor using CMB lensing kernel.
    """
    z_star = 1100  # CMB redshift
    chi_g = comoving_distance_proper(z_g, H0, Om0, Om_lambda)
    chi_star = comoving_distance_proper(z_star, H0, Om0, Om_lambda)

    # Lensing efficiency using proper CMB kernel
    W_k = cmb_lensing_kernel(z_g, z_star, H0, Om0, Om_lambda)

    # Normalize by a characteristic value
    W_k_norm = cmb_lensing_kernel(z_k, z_star, H0, Om0, Om_lambda)

    return W_k / (W_k_norm + 1e-10)  # Avoid division by zero

def compute_lensing_efficiency(z_g, z_k, H0, Om0):
    """
    Compute lensing efficiency factor.
    Fixed: Proper lensing kernel computation.
    """
    chi_g = comoving_distance(z_g, H0, Om0)
    chi_k = comoving_distance(z_k, H0, Om0)

    # CMB is at much higher redshift, so chi_star >> chi_g
    chi_star = 14000  # Approximate comoving distance to CMB (Mpc)

    # Lensing efficiency: (chi_star - chi_g) / chi_star
    if chi_g < chi_star:
        return (chi_star - chi_g) / chi_star
    else:
        return 0.0

# # Covariance Matrix for Galaxy–CMB Lensing Cross-Correlation
# # Covariance Matrix
# # Computes the covariance matrix for the cross-correlation measurements, accounting for cosmic variance and survey area

# def compute_realistic_covariance(C_gg, C_gk, C_kk, ell, f_sky=0.1):
#     """
#     Compute realistic covariance matrix for galaxy-CMB cross-correlation.
#     Using the correct formula: Cov(C_gg, C_gk) = δ_ℓℓ'/(2ℓ+1) * [C_gk * C_gg + C_gg * C_gk]
#     """
#     # Ensure all arrays have the same length
#     min_len = min(len(C_gg), len(C_gk), len(C_kk))
#     C_gg = C_gg[:min_len]
#     C_gk = C_gk[:min_len]
#     C_kk = C_kk[:min_len]
#     ell = ell[:min_len]

#     # Correct covariance formula: Cov(C_gg, C_gk) = δ_ℓℓ'/(2ℓ+1) * [C_gk * C_gg + C_gg * C_gk]
#     # Since C_gk * C_gg = C_gg * C_gk, this simplifies to: 2 * C_gk * C_gg / (2ℓ+1)
#     # Including f_sky factor: divide by f_sky
#     cov_diag = (2 * C_gk * C_gg) / ((2 * ell + 1) * f_sky)

#     # Add small noise floor to prevent numerical issues
#     cov_diag = np.maximum(cov_diag, 1e-10 * np.abs(C_gk)**2)

#     return cov_diag

def compute_realistic_covariance(C_gg, C_gk, C_kg, ell):
    """
    Compute realistic covariance vector for galaxy-CMB cross-correlation.
    Formula used: Cov(C_gg, C_gk) = [C_gk * C_gg + C_gg * C_kg] / (2ℓ + 1)
    Assumes C_kg ≠ C_gk (i.e., not symmetric).
    """
    # Ensure all arrays have the same length
    min_len = min(len(C_gg), len(C_gk), len(C_kg), len(ell))
    C_gg = C_gg[:min_len]
    C_gk = C_gk[:min_len]
    C_kg = C_kg[:min_len]
    ell = ell[:min_len]

    # Compute covariance vector using the specified formula
    cov_diag = (C_gk * C_gg + C_gg * C_kg) / (2 * ell + 1)

    # Add small noise floor to avoid numerical issues
    cov_diag = np.maximum(cov_diag, 1e-10 * np.abs(C_gk * C_kg))

    return cov_diag

# Likelihood Function
# Computes the log-likelihood by comparing theoretical predictions with observed data using a chi-squared statistic
# --- Step 3: Define Likelihood Function ---
def log_likelihood(params):
    """
    Compute log-likelihood for galaxy-CMB cross-correlation.
    Fixed: Proper likelihood computation with error handling.
    """
    try:
        H0, ombh2, omch2, ns, As = params

        # Derived parameters
        h = H0 / 100.0
        Om0 = (ombh2 + omch2) / h**2

        # Bounds checking
        if not (0.1 < Om0 < 1.0):
            return -np.inf
        if not (1e-11 < As < 1e-8):
            return -np.inf

        # Compute power spectra at both redshifts
        P_k_g = run_cosmopower(H0, ombh2, omch2, ns, As, z_g)
        P_k_k = run_cosmopower(H0, ombh2, omch2, ns, As, z_k)

        # Compute cross-correlation spectrum
        ell, C_gk_model = galaxy_cmb_cross_spectrum(P_k_g, P_k_k, z_g, z_k, H0, Om0)

        # Ensure same length as data
        if len(C_gk_model) != len(C_true):
            min_len = min(len(C_gk_model), len(C_true))
            C_gk_model = C_gk_model[:min_len]
            C_true_use = C_true[:min_len]
            inv_cov_use = inv_cov[:min_len, :min_len]
        else:
            C_true_use = C_true
            inv_cov_use = inv_cov

        # Compute likelihood
        diff = C_gk_model - C_true_use
        chi2 = np.dot(diff, np.dot(inv_cov_use, diff))

        return -0.5 * chi2

    except Exception as e:
        print(f"Error in likelihood calculation: {e}")
        return -np.inf

"""## Main analysis pipeline by establishing parameters, computing theoretical spectra, and preparing data for statistical inference.


### Initial Parameter Setup
The analysis begins by defining key observational parameters:
- **Galaxy redshift** (`z_g = 0.5`): The redshift of the galaxy sample being analyzed
- **Effective lensing redshift** (`z_k = 1.0`): The characteristic redshift for CMB lensing effects
- **Maximum multipole** (`lmax = 1000`): The angular scale cutoff.

### Cosmological Parameter Extraction
The code extracts fiducial (reference) cosmological parameters from a pre-existing parameter dictionary:
- `omega_b`: Baryon density parameter
- `omega_cdm`: Cold dark matter density parameter  
- `h`: Reduced Hubble parameter
- `n_s`: Scalar spectral index
- `ln10^{10}A_s`: Logarithm of the primordial power spectrum amplitude

### Parameter Format Conversion
The extracted parameters are converted to the specific format required by the analysis functions:
- **Hubble constant**: `H0 = h × 100.0` km/s/Mpc
- **Baryon density**: `Ωb h²`
- **CDM density**: `Ωc h²`
- **Primordial amplitude**: `As = exp(ln10^{10}As) / 10^10`

### Derived Cosmological Parameters
Additional parameters are calculated assuming a flat ΛCDM cosmology:
- **Total matter density**: `Ωm = Ωb + Ωcdm`
- **Dark energy density**: `ΩΛ = 1 - Ωm` (flat universe assumption)

### Fiducial Spectra Generation
The code generates theoretical power spectra at the fiducial cosmological parameters:
- **Galaxy power spectrum** `P(k,z_g)` at galaxy redshift
- **Lensing power spectrum** `P(k,z_k)` at lensing redshift

These represent the "true" underlying cosmology for the analysis.

### Angular Power Spectrum Computation
Using Limber projection, the code converts 3D power spectra to 2D angular correlations:
- **Galaxy auto-correlation**: `C_gg(ℓ)` - galaxy clustering signal
- **Lensing auto-correlation**: `C_kk(ℓ)` - CMB lensing auto-spectrum  
- **Galaxy-lensing cross-correlation**: `C_gk(ℓ)` - the primary observable

### Statistical Analysis Preparation

#### Covariance Matrix
A realistic covariance matrix is computed accounting for:
- Cosmic variance
- Shot noise
- Survey geometry (sky fraction `f_sky = 0.1`)

#### Data Quality Control
The code implements robust data filtering:
- Removes non-finite values
- Excludes zero-variance data points
- Filters out negligibly small cross-correlation values (`|C_gk| > 10^-12`)
- Creates fallback minimal dataset if no valid points are found

#### Matrix Inversion
The covariance matrix is inverted for chi-squared analysis:
- Attempts standard matrix inversion
- Falls back to pseudo-inverse for singular matrices
- Provides diagnostic information about matrix conditioning

### Validation and Testing
The code concludes by testing enhanced cosmological functions:
- **Growth factor** `D(z)`: Matter density perturbation growth
- **CMB lensing kernel** `W_k(z)`: Lensing efficiency function  
- **Galaxy bias** `b(z)`: Relationship between galaxy and matter overdensities
"""

# # --- Step 4: Main Analysis ---
# # Set parameters
# z_g = 0.5  # Galaxy redshift
# z_k = 1.0  # Effective lensing redshift
# lmax = 1000  #lmax = 200 (took 5 minutes) (The highest ℓ (multipole) value used in the calculations.
#                                            # Decides how many angular scales (details on the sky) are included

# # Extract fiducial cosmological parameters from the params dictionary
# omega_b_fid = params['omega_b'][0]
# omega_cdm_fid = params['omega_cdm'][0]
# h_fid = params['h'][0]
# ns_fid = params['n_s'][0]
# ln10_10_As_fid = params['ln10^{10}A_s'][0]

# # Convert to the format needed by the analysis (Parameter Conversion)
# # Converts parameters from the dictionary format to the format needed for the analysis
# H0_fid = h_fid * 100.0
# ombh2_fid = omega_b_fid * h_fid**2
# omch2_fid = omega_cdm_fid * h_fid**2
# As_fid = np.exp(ln10_10_As_fid) / 1e10

# # Derived parameters
# Om0_fid = omega_b_fid + omega_cdm_fid
# Om_lambda_fid = 1 - Om0_fid  # Assuming flat universe

# print(f"Using parameters from dictionary:")
# print(f"H0 = {H0_fid:.1f} km/s/Mpc")
# print(f"Omega_b h^2 = {ombh2_fid:.5f}")
# print(f"Omega_c h^2 = {omch2_fid:.5f}")
# print(f"n_s = {ns_fid:.4f}")
# print(f"A_s = {As_fid:.2e}")
# print(f"Omega_m = {Om0_fid:.4f}")
# print(f"Omega_lambda = {Om_lambda_fid:.4f}")
# print(f"alpha = {alpha:.3f}")

# # Generate fiducial spectra
# # Generates the "true" data by computing power spectra at fiducial cosmological parameters
# print("Computing fiducial spectra...")
# P_k_g_fid = run_cosmopower(H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid, z_g)
# P_k_k_fid = run_cosmopower(H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid, z_k)

# # Data Preparation
# # Compute auto and cross-correlations
# # Computes auto- and cross-correlation spectra that serve as the "observed" data

# ell, C_gg_fid = limber_projection(P_k_g_fid, z_g, H0_fid, Om0_fid, lmax)
# _, C_kk_fid = limber_projection(P_k_k_fid, z_k, H0_fid, Om0_fid, lmax)
# _, C_gk_fid = galaxy_cmb_cross_spectrum(P_k_g_fid, P_k_k_fid, z_g, z_k, H0_fid, Om0_fid, lmax=lmax)

# # Compute covariance matrix
# print("Computing covariance matrix...")
# cov_diag = compute_realistic_covariance(C_gg_fid, C_gk_fid, C_kk_fid, ell, f_sky=0.1)

# # Create mask for valid data points
# mask = np.isfinite(cov_diag) & (cov_diag > 0) & (np.abs(C_gk_fid) > 1e-12)

# if not np.any(mask):
#     print("Warning: No valid data points found.")
#     # Create minimal valid dataset
#     mask = np.ones(min(50, len(C_gk_fid)), dtype=bool)
#     if len(mask) < len(C_gk_fid):
#         mask = np.concatenate([mask, np.zeros(len(C_gk_fid) - len(mask), dtype=bool)])

# # Apply mask
# ell_use = ell[mask]
# C_true = C_gk_fid[mask]
# cov_matrix = np.diag(cov_diag[mask])

# print(f"Using {len(C_true)} data points")
# print(f"ell range: {ell_use[0]:.0f} to {ell_use[-1]:.0f}")

# # Invert covariance matrix
# try:
#     inv_cov = np.linalg.inv(cov_matrix)
#     print("Covariance matrix successfully inverted")
# except np.linalg.LinAlgError:
#     print("Covariance matrix singular, using regularized version")
#     inv_cov = np.linalg.pinv(cov_matrix)

# # Test the new functions
# print("\nTesting enhanced functions:")
# print(f"Growth factor D(z=0.5) = {growth_factor_D(0.5, H0_fid, Om0_fid, Om_lambda_fid):.4f}")
# print(f"CMB lensing kernel W_k(z=0.5) = {cmb_lensing_kernel(0.5, 1100, H0_fid, Om0_fid, Om_lambda_fid):.2e}")
# print(f"Bias function b(z=0.5) = {bias_function(0.5):.4f}")

# --- Step 4: Main Analysis ---

# Define the covariance computation function
# (galaxy overdensity (denoted by g) and CMB lensing convergence (denoted by κ))
def compute_cov_vector(C_gg, C_gk, C_kg, ell):
    return (C_gk * C_gg + C_gg * C_kg) / (2 * ell + 1) # Assuming δ_ℓℓ′ = 1, i.e., only diagonal covariance is considered (ℓ = ℓ′)


# Set parameters
z_g = 0.5  # Galaxy redshift
z_k = 1.0  # Effective lensing redshift
lmax = 1000  # Maximum multipole used in the analysis

# Extract fiducial cosmological parameters from the params dictionary
omega_b_fid = params['omega_b'][0]
omega_cdm_fid = params['omega_cdm'][0]
h_fid = params['h'][0]
ns_fid = params['n_s'][0]
ln10_10_As_fid = params['ln10^{10}A_s'][0]

# Convert to required format
H0_fid = h_fid * 100.0
ombh2_fid = omega_b_fid * h_fid**2
omch2_fid = omega_cdm_fid * h_fid**2
As_fid = np.exp(ln10_10_As_fid) / 1e10

# Derived parameters
Om0_fid = omega_b_fid + omega_cdm_fid
Om_lambda_fid = 1 - Om0_fid  # Flat universe

print(f"Using parameters from dictionary:")
print(f"H0 = {H0_fid:.1f} km/s/Mpc")
print(f"Omega_b h^2 = {ombh2_fid:.5f}")
print(f"Omega_c h^2 = {omch2_fid:.5f}")
print(f"n_s = {ns_fid:.4f}")
print(f"A_s = {As_fid:.2e}")
print(f"Omega_m = {Om0_fid:.4f}")
print(f"Omega_lambda = {Om_lambda_fid:.4f}")
print(f"alpha = {alpha:.3f}")

# Generate fiducial spectra
print("Computing fiducial spectra...")
P_k_g_fid = run_cosmopower(H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid, z_g)
P_k_k_fid = run_cosmopower(H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid, z_k)

# Compute angular power spectra
ell, C_gg_fid = limber_projection(P_k_g_fid, z_g, H0_fid, Om0_fid, lmax)
_, C_kk_fid = limber_projection(P_k_k_fid, z_k, H0_fid, Om0_fid, lmax)
_, C_gk_fid = galaxy_cmb_cross_spectrum(P_k_g_fid, P_k_k_fid, z_g, z_k, H0_fid, Om0_fid, lmax=lmax)

# Compute covariance matrix using the defined function
print("Computing covariance matrix...")
cov_diag = compute_cov_vector(C_gg_fid, C_gk_fid, C_gk_fid, ell)

# Create mask for valid data points
mask = np.isfinite(cov_diag) & (cov_diag > 0) & (np.abs(C_gk_fid) > 1e-12)

if not np.any(mask):
    print("Warning: No valid data points found.")
    # Create minimal valid dataset
    mask = np.ones(min(50, len(C_gk_fid)), dtype=bool)
    if len(mask) < len(C_gk_fid):
        mask = np.concatenate([mask, np.zeros(len(C_gk_fid) - len(mask), dtype=bool)])

# Apply mask
ell_use = ell[mask]
C_true = C_gk_fid[mask]
cov_matrix = np.diag(cov_diag[mask])

print(f"Using {len(C_true)} data points")
print(f"ell range: {ell_use[0]:.0f} to {ell_use[-1]:.0f}")

# Invert covariance matrix
try:
    inv_cov = np.linalg.inv(cov_matrix)
    print("Covariance matrix successfully inverted")
except np.linalg.LinAlgError:
    print("Covariance matrix singular, using regularized version")
    inv_cov = np.linalg.pinv(cov_matrix)

# Test outputs
print("\nTesting enhanced functions:")
print(f"Growth factor D(z=0.5) = {growth_factor_D(0.5, H0_fid, Om0_fid, Om_lambda_fid):.4f}")
print(f"CMB lensing kernel W_k(z=0.5) = {cmb_lensing_kernel(0.5, 1100, H0_fid, Om0_fid, Om_lambda_fid):.2e}")
print(f"Bias function b(z=0.5) = {bias_function(0.5):.4f}")

# Inverts covariance matrix with optional regularization for stability.

def invert_covariance_matrix(cov_matrix, regularization_factor=1e-10):
    try:
        # Check condition number of the matrix
        cond_number = np.linalg.cond(cov_matrix)
        print(f"Condition number of covariance matrix: {cond_number}")

        if cond_number > 1 / np.finfo(cov_matrix.dtype).eps:
            print("Warning: Covariance matrix is nearly singular. Applying regularization.")
            # Add a small regularization term to the diagonal to stabilize inversion
            cov_matrix_regularized = cov_matrix + np.eye(cov_matrix.shape[0]) * regularization_factor
            inv_cov = np.linalg.inv(cov_matrix_regularized)
            print("Regularized matrix inversion successful.")
        else:
            # Invert the covariance matrix directly
            inv_cov = np.linalg.inv(cov_matrix)
            print("Matrix inversion successful without regularization.")
        return inv_cov
    except np.linalg.LinAlgError:
        # Fallback if inversion fails (e.g., matrix is singular)
        print("Matrix inversion failed, falling back to pseudoinverse.")
        inv_cov = np.linalg.pinv(cov_matrix)
        return inv_cov

# Example covariance matrix (replace with actual data)
cov_matrix = np.array([[1.0, 0.5], [0.5, 1.0]])

# Invert covariance matrix with regularization
inv_cov_matrix = invert_covariance_matrix(cov_matrix)
print(f"Inverted Covariance Matrix: \n{inv_cov_matrix}")

# Test outputs
print("\nTesting enhanced functions:")
print(f"Growth factor D(z=0.5) = {growth_factor_D(0.5, H0_fid, Om0_fid, Om_lambda_fid):.4f}")
print(f"CMB lensing kernel W_k(z=0.5) = {cmb_lensing_kernel(0.5, 1100, H0_fid, Om0_fid, Om_lambda_fid):.2e}")
print(f"Bias function b(z=0.5) = {bias_function(0.5):.4f}")

"""## Priors Used in MCMC Sampling

The following prior distributions were used for the cosmological parameters in the MCMC analysis:

| Parameter               | Symbol        | Distribution Type | Center (Mean)       | Width / Range                     | Python Representation                          |
|-------------------------|---------------|-------------------|----------------------|------------------------------------|------------------------------------------------|
| Hubble constant         | H₀            | Uniform            | H₀_fid ± 10          | Range = [H₀_fid - 10, H₀_fid + 10] | `uniform(loc=H0_fid - 10, scale=20)`           |
| Baryon density          | Ω<sub>b</sub>h² | Normal             | ombh2_fid            | σ = 0.003                          | `norm(loc=ombh2_fid, scale=0.003)`             |
| Cold dark matter density| Ω<sub>c</sub>h² | Normal             | omch2_fid            | σ = 0.015                          | `norm(loc=omch2_fid, scale=0.015)`             |
| Scalar spectral index   | n<sub>s</sub>  | Normal             | ns_fid               | σ = 0.015                          | `norm(loc=ns_fid, scale=0.015)`                |
| Scalar amplitude        | A<sub>s</sub>  | Normal             | As_fid               | σ = 3 × 10⁻¹⁰                     | `norm(loc=As_fid, scale=3e-10)`                |

---

### 🔸 Prior Definition in Code

```python
prior = pc.Prior([
    uniform(loc=H0_fid - 10, scale=20),              # H₀
    norm(loc=ombh2_fid, scale=0.003),                # Ω_b h²
    norm(loc=omch2_fid, scale=0.015),                # Ω_c h²
    norm(loc=ns_fid, scale=0.015),                   # nₛ
    norm(loc=As_fid, scale=3e-10)                    # Aₛ
])

```

---

| Parameter   | Type    | Mean         | Range / Std Dev | Short Description                                 |
| ----------- | ------- | ------------ | ---------------- | ------------------------------------------------- |
| **H₀**      | Uniform | 70.0         | [60.0, 80.0]     | Hubble constant — present-day expansion rate      |
| **Ω_b h²**  | Normal  | 0.011025     | ± 0.003          | Physical baryon density                           |
| **Ω_c h²**  | Normal  | 0.055405     | ± 0.015          | Physical cold dark matter density                 |
| **nₛ**      | Normal  | 0.96         | ± 0.015          | Spectral index of scalar perturbations            |
| **Aₛ**      | Normal  | 2.351 × 10⁻⁹ | ± 3 × 10⁻¹⁰      | Amplitude of primordial curvature perturbations   |



"""

# --- Step 5: Set up MCMC --- MCMC Sampling
print("Setting up MCMC...")

# Prior Setup
# Define priors centered around the fiducial values from params dictionary
# Sets up prior distributions for each parameter - uniform for H₀, normal for others
prior = pc.Prior([
    uniform(loc=H0_fid-10, scale=20),              # H0 ∈ [H0_fid-10, H0_fid+10]
    norm(loc=ombh2_fid, scale=0.003),              # ombh2
    norm(loc=omch2_fid, scale=0.015),              # omch2
    norm(loc=ns_fid, scale=0.015),                 # ns
    norm(loc=As_fid, scale=3e-10)                  # As
])

# Test likelihood at fiducial values
print("Testing likelihood at fiducial values...")
test_params = [H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid]
test_loglike = log_likelihood(test_params)
print(f"Log-likelihood at fiducial values: {test_loglike:.2f}")

# Run MCMC (Sampler Execution)
# Runs the MCMC sampling using the PocOMC sampler to explore the posterior distribution
print("Running MCMC...")
sampler = pc.Sampler(
    prior=prior,
    likelihood=log_likelihood,
    vectorize=False,
    random_state=42
)

# Initialize samples as None before running the sampler
samples = None

try:
    # Assuming `sampler` is already set up and ready
    sampler.run()  # Run MCMC sampler
    samples, weights, logl, logp = sampler.posterior()  # Extract posterior samples from the sampler
except Exception as e:
    print(f"An error occurred during sampling: {e}")
    samples = None  # Set samples to None if an error occurs during the sampling

# Check if samples array is empty after running the sampler
if samples is None or len(samples) == 0 or samples.size == 0:
    print("Error: The 'samples' array is empty!")
else:
    # Apply burn-in removal only if the array is not empty
    burn_in = int(0.1 * len(samples))  # Discard first 10% as burn-in (discarding 10% of the chain to ensure reliable inference from the remaining 90%)
    samples = samples[burn_in:]
    weights = weights[burn_in:]
    logl = logl[burn_in:]
    logp = logp[burn_in:]

    print(f"Removed {burn_in} burn-in samples")

# import pocomc as pc
# from scipy.stats import uniform, norm

# --- Uniform Priors ---
# uniform_prior = pc.Prior([
#     uniform(loc=H0_fid - 10, scale=20),        # H0 ∈ [H0_fid - 10, H0_fid + 10]
#     uniform(loc=ombh2_fid - 0.003, scale=0.006),  # Ω_b h² ∈ [fid - 0.003, fid + 0.003]
#     uniform(loc=omch2_fid - 0.015, scale=0.030),  # Ω_c h² ∈ [fid - 0.015, fid + 0.015]
#     uniform(loc=ns_fid - 0.015, scale=0.030),     # n_s ∈ [fid - 0.015, fid + 0.015]
#     uniform(loc=As_fid - 3e-10, scale=6e-10)      # A_s ∈ [fid - 3e-10, fid + 3e-10]
# ])

# --- Normal Priors ---
# normal_prior = pc.Prior([
#     norm(loc=H0_fid, scale=5),                  # Assume ±5 uncertainty
#     norm(loc=ombh2_fid, scale=0.003),
#     norm(loc=omch2_fid, scale=0.015),
#     norm(loc=ns_fid, scale=0.015),
#     norm(loc=As_fid, scale=3e-10)
# ])

#Code for Both Priors:

# # Choose one of the two priors (comment/uncomment as needed)
# prior = uniform_prior   # Use this for uniform prior
# # prior = normal_prior  # Use this for normal prior

# # Test likelihood at fiducial values
# print("Testing likelihood at fiducial values...")
# test_params = [H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid]
# test_loglike = log_likelihood(test_params)
# print(f"Log-likelihood at fiducial values: {test_loglike:.2f}")

# # Run MCMC (Sampler Execution)
# print("Running MCMC...")
# sampler = pc.Sampler(
#     prior=prior,                      # Now refers to selected prior
#     likelihood=log_likelihood,
#     vectorize=False,
#     random_state=42
# )

# sampler.run()
# samples, weights, logl, logp = sampler.posterior()
# print(f"Generated {len(samples)} samples")

# run both priors one after the other and compare results

# for prior_name, prior in [("Uniform", uniform_prior), ("Normal", normal_prior)]:
#     print(f"\n--- Running MCMC with {prior_name} Prior ---")
#     sampler = pc.Sampler(
#         prior=prior,
#         likelihood=log_likelihood,
#         vectorize=False,
#         random_state=42
#     )
#     sampler.run()
#     samples, weights, logl, logp = sampler.posterior()
#     print(f"{prior_name} Prior: Generated {len(samples)} samples")

# --- Step 6: Analyze Results ---
params_names = ["H₀", "Ωbh²", "Ωch²", "nₛ", "Aₛ"]
fiducial_values = [H0_fid, ombh2_fid, omch2_fid, ns_fid, As_fid]

# Results Analysis
# Compute posterior statistics
# Computes posterior mean and standard deviation for each parameter, providing constraints on cosmological parameters
means = np.average(samples, axis=0, weights=weights)
stds = np.sqrt(np.average((samples - means)**2, axis=0, weights=weights))

print("\nPosterior Summary:")
print("Parameter     | Fiducial | Posterior Mean ± Std")
print("-" * 50)
for i, name in enumerate(params_names):
    print(f"{name:12s} | {fiducial_values[i]:8.5f} | {means[i]:8.5f} ± {stds[i]:8.5f}")

# --- Step 7: Create Plots ---
print("Creating plots...")

# Plot posterior for H0
plt.figure(figsize=(8, 6))
plt.hist(samples[:, 0], bins=40, weights=weights, density=True,
         alpha=0.7, label='Posterior', color='dodgerblue')
plt.axvline(H0_fid, color='red', linestyle='--', label=f'True H₀ = {H0_fid:.1f}')
plt.xlabel(r'$H_0$ [km/s/Mpc]', fontsize=14)
plt.ylabel('Posterior Density', fontsize=14)
plt.title('Posterior for $H_0$', fontsize=16, fontweight='bold')
plt.legend()
plt.grid(True)

# Save and show the figure
plt.savefig('plots/posterior_H0.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Step 8: Additional Analysis Plots ---
print("\nCreating additional analysis plots...")

# Plot 1: Trace plots to check MCMC convergence
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
axes = axes.flatten()

# Create trace plots for each parameter
for i, name in enumerate(params_names):
    if i < len(axes):
        axes[i].plot(samples[:, i], alpha=0.7, linewidth=0.5)
        axes[i].axhline(y=fiducial_values[i], color='red', linestyle='--',
                       label=f'Fiducial: {fiducial_values[i]:.4f}')
        axes[i].set_title(f'{name} Trace')
        axes[i].set_xlabel('Sample Number')
        axes[i].set_ylabel(name)
        axes[i].legend()
        axes[i].grid(True, alpha=0.3)

# Remove empty subplot
if len(params_names) < len(axes):
    fig.delaxes(axes[-1])

plt.tight_layout()
plt.savefig('plots/trace_plots.png', dpi=300, bbox_inches='tight')
plt.show()

# --- Step 9: Create Corner Plot ---
print("\nCreating corner plots...")

# 9A. corner.py plot
try:

    fig = corner.corner(
        samples,
        labels=params_names,
        truths=fiducial_values,
        weights=weights,
        show_titles=True,
        title_kwargs={"fontsize": 12},
        quantiles=[0.16, 0.5, 0.84],
        title_fmt='.4f',
        smooth=1.0,
        bins=30,
        color='blue',
        truth_color='red',
        hist_kwargs={'density': True, 'alpha': 0.7},
        scatter_kwargs={'alpha': 0.3, 's': 10}
    )

    fig.suptitle('Galaxy-CMB Cross-Correlation: Posterior Distributions',
                 fontsize=16, y=0.98)

    plt.savefig('plots/corner_plot_corner.png', dpi=300, bbox_inches='tight')
    plt.show()

except Exception as e:
    print(f"corner.py plot failed: {e}")

# 9B. GetDist plot
try:
    from getdist import MCSamples, plots as gd_plots

    print("Creating GetDist triangle plot...")

    samples_gd = MCSamples(samples=samples, weights=weights, names=params_names, labels=params_names)

    g = gd_plots.get_subplot_plotter()
    g.triangle_plot([samples_gd], filled=True, contour_colors=['blue'],
                    markers=dict(zip(params_names, fiducial_values)))

    plt.savefig('plots/corner_plot_getdist.png', dpi=300, bbox_inches='tight')
    plt.show()

except Exception as e:
    print(f"GetDist plot failed: {e}")

# --- Step 10: Corner Plot (Parameter Correlations) Plot ---
print("Creating corner plots...")

# Try GetDist first
try:
    from getdist import MCSamples, plots

    # Create MCSamples object for GetDist
    mc_samples = MCSamples(samples=samples, weights=weights, names=params_names)

    # Create corner plot using GetDist
    g = plots.get_subplot_plotter()
    g.triangle_plot([mc_samples], filled=True,
                    markers=dict(zip(params_names, fiducial_values)),
                    colors=['blue'])
    g.export("plots/corner_plot_getdist.png")
    plt.show()

except Exception as e:
    print(f"GetDist corner plot failed: {e}")

# Use corner (corner.py) as a backup regardless
try:
    import corner

    print("Creating corner plot using `corner`")

    figure = corner.corner(
        samples,
        labels=params_names,
        truths=fiducial_values,
        weights=weights,
        show_titles=True,
        title_fmt=".4f",
        color='dodgerblue'
    )

    figure.suptitle("Corner Plot of Posterior Samples", fontsize=16)
    figure.tight_layout()
    figure.savefig("plots/corner_plot_corner.png", dpi=300)
    plt.show()

except Exception as e:
    print(f"corner.py plot failed: {e}")