# -*- coding: utf-8 -*-
"""core_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uz1Cv6-G7_sqYaVte1Uk2GkBTQZeha6Q
"""

import numpy as np
from scipy.integrate import quad
from astropy.cosmology import FlatLambdaCDM

# Physical constants
c = 299792.458  # km/s
alpha = 2.225   # magnification bias parameter

def hubble_function(z, H0, Om_m, Om_lambda):
    return H0 * np.sqrt(Om_m * (1 + z)**3 + Om_lambda)

def comoving_distance_proper(z, H0, Om_m, Om_lambda):
    def integrand(z_prime):
        return c / hubble_function(z_prime, H0, Om_m, Om_lambda)
    chi, _ = quad(integrand, 0, z)
    return chi

def compute_Omega_z(z, H0, Om_m, Om_lambda):
    numerator = Om_m * (1 + z)**3
    denominator = numerator + (1 - Om_m - Om_lambda) * (1 + z)**2 + Om_lambda
    return numerator / denominator

def compute_lambda_z(z, H0, Om_m, Om_lambda):
    denominator = Om_m * (1 + z)**3 + (1 - Om_m - Om_lambda) * (1 + z)**2 + Om_lambda
    return Om_lambda / denominator

def growth_function_g(z, H0, Om_m, Om_lambda):
    Omega_z = compute_Omega_z(z, H0, Om_m, Om_lambda)
    lambda_z = compute_lambda_z(z, H0, Om_m, Om_lambda)
    denom = Omega_z**(4/7) - lambda_z + (1 + Omega_z/2) * (1 + lambda_z/70)
    return (5 * Omega_z / 2) / denom

def growth_factor_D(z, H0, Om_m, Om_lambda):
    return growth_function_g(z, H0, Om_m, Om_lambda) / (1 + z)

def cmb_lensing_kernel(z, z_star, H0, Om_m, Om_lambda):
    chi_z = comoving_distance_proper(z, H0, Om_m, Om_lambda)
    chi_star = comoving_distance_proper(z_star, H0, Om_m, Om_lambda)
    prefactor = (3 * Om_m * H0**2) / (2 * c)
    return prefactor * (1 + z) * chi_z * (chi_star - chi_z) / chi_star

def galaxy_number_density(z):
    z0 = 0.3
    return np.exp(-z/z0)

def bias_function(z):
    b0 = 1.0
    D_star_z = growth_factor_D(z, 70.0, 0.3, 0.7) / growth_factor_D(0, 70.0, 0.3, 0.7)
    return b0 / D_star_z

def galaxy_lensing_kernel(z, z_array, dN_dz_func, bias_func, H0, Om_m, Om_lambda):
    bias_term = bias_func(z) * dN_dz_func(z)
    chi_z = comoving_distance_proper(z, H0, Om_m, Om_lambda)
    def integrand(z_prime):
        chi_z_prime = comoving_distance_proper(z_prime, H0, Om_m, Om_lambda)
        return (1 - chi_z / chi_z_prime) * (alpha - 1) * dN_dz_func(z_prime)
    z_star = 10.0
    integral_term, _ = quad(integrand, z, z_star)
    mu_prefactor = (3 * Om_m * H0**2) / (2 * c) * (1 + z) * chi_z
    mu_z = mu_prefactor * integral_term
    return bias_term + mu_z

def compute_lensing_efficiency_proper(z_g, z_k, H0, Om0, Om_lambda):
    z_star = 1100
    W_k = cmb_lensing_kernel(z_g, z_star, H0, Om0, Om_lambda)
    W_k_norm = cmb_lensing_kernel(z_k, z_star, H0, Om0, Om_lambda)
    return W_k / (W_k_norm + 1e-10)

def comoving_distance(z, H0, Om0):
    cosmo = FlatLambdaCDM(H0=H0, Om0=Om0)
    return cosmo.comoving_distance(z).value